### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry-community/terraform-aws-cf-install#16]
When creating the environment, the cf_api of that terraform spits out is slightly different than the required syntax.  Terraform gives the parameter as "api.x.x.x.x.xip.io" and the actual endpoint needs to be "api.run.x.x.x.x.xip.io".

Also it may be worth noting in the instructions that the script will take a long time (over an hour) to run.  Without intermediate feedback it seems like the script stalls.

**Comment by teancom** [comment]
Thanks for the feedback! It's awesome to know that it's not just me and @longnguyen11288 using this :smile:

**Comment by longnguyen11288** [comment]
Yay!
