### ISSUE TITLE
CF AZ's to configurable AWS AZ's

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry-community/terraform-aws-cf-install#18]
By default the script creates both cf zones in the same AWS AZ.  I would like to have the zones be different AZ's in the same region, configurable via parameters in the var file.  

I realize for the cf-tiny deployment, fail-over/redundancy is not crucial.  But this would afford some level of redundancy as we deploy multiple runners or if we move into a cf-large deployment with redundant instances.

I have a working fork of this in my github account, what do you guys think of adding this configuration option?

**Comment by teancom** [comment]
Absolutely. Doing that has been on my "would be really nice to get around to this" list for a while. PR definitely accepted.

**Comment by teancom** [comment]
Done (by you!) in PR #19
