### ISSUE TITLE
Security group broken

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry-community/terraform-aws-cf-install#23]
In provision.sh script, there is a typo causing security groups to not get created.  Line 21 needs to be CF_SG=${15}  instead of the current CF_AG=${15}

**Comment by teancom** [comment]
We actually literally just noticed this 30 minutes ago. This will be fixed very shortly.

**Comment by teancom** [comment]
This was just fixed in https://github.com/cloudfoundry-community/terraform-aws-cf-install/pull/22 Thanks for the report!
