### ISSUE TITLE
Address 10.x.1.4 is in use. (AWS::EC2::Errors::InvalidIPAddress::InUse)

### ISSUE THREAD

**Issue by mdcarlson** [cloudfoundry-community/terraform-aws-cf-install#32]
I've re-run my "terraform apply" multiple times getting past various dependency issues.

Now, during the "deploy micro bosh" step, I'm hitting an address in use error.

Not quite sure what to clean up to get past this.

    aws_instance.bastion (remote-exec): Stemcell info
    aws_instance.bastion (remote-exec): -------------
    aws_instance.bastion (remote-exec): Name:    bosh-aws-xen-ubuntu-trusty-go_agent
    aws_instance.bastion (remote-exec): Version: 2905

    aws_instance.bastion (remote-exec):   Started deploy micro bosh
    aws_instance.bastion (remote-exec):   Started deploy micro bosh > Unpacking stemcell. Done (00:00:00)
    aws_instance.bastion (remote-exec):   Started deploy micro bosh > Uploading stemcell
    aws_instance.bastion (remote-exec): . Done (00:00:04)
    aws_instance.bastion (remote-exec):   Started deploy micro bosh > Creating VM from ami-b88da7d0 light
    aws_instance.bastion (remote-exec): log writing failed. can't be called from trap context
    aws_instance.bastion (remote-exec): /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise': Address 10.x.1.4 is in use. (AWS::EC2::Errors::InvalidIPAddress::InUse)

**Comment by longnguyen11288** [comment]
You might have microbosh already running, look in AWS console to see if its already running.

**Comment by mdcarlson** [comment]
As you suggested, there was a microbosh already running.  What is the appropriate workaround / recovery for this scenario?   I nuked the microbosh and and re-running again, but undoubtedly, there was a better approach.

**Comment by longnguyen11288** [comment]
Currently there isn't a better way. I would like to make the provision script be able to pick up where it left off but haven't had time to look into that.
