### ISSUE TITLE
Error installing large version of Cloud Foundry

### ISSUE THREAD

**Issue by mminges** [cloudfoundry-community/terraform-aws-cf-install#41]
When attempting a large deploy of Cloud Foundry I have been running into an unresolved node error as a result of a spiff merge command:

aws_instance.bastion (remote-exec):  1 file changed, 14 insertions(+), 14 deletions(-)
aws_instance.bastion (remote-exec): Generating deployment manifest
aws_instance.bastion (remote-exec): Command failed: 'spiff merge /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-deployment.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-jobs.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-uaa-port.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-properties.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-infrastructure-aws.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf/cf-minimal-dev.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-runners.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-single-az.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-no-ssl.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-test-errands.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-properties.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-haproxy.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-postgresql.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-nfs.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-secrets.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-networking.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-deployment-size.yml /home/ubuntu/workspace/deployments/cf-boshworkspace/.stubs/cf-aws-large.yml 2>&1'
aws_instance.bastion (remote-exec): 2015/04/13 15:49:29 error generating manifest: unresolved nodes:
aws_instance.bastion (remote-exec): 	(( static_ips(0) ))	in /home/ubuntu/workspace/deployments/cf-boshworkspace/templates/cf-use-haproxy.yml	jobs.[0].networks.[1].static_ips
aws_instance.bastion (remote-exec): 
aws_instance.bastion: Error: 1 error(s) occurred:

Any thoughts on how to debug this?

**Comment by longnguyen11288** [comment]
Hmm I haven't looked into large in a while, when I get a chance this week I'll try to fix it.

**Comment by longnguyen11288** [comment]
Hi there! i fixed the issue, it should be ready to deploy with latest version of terraform aws cf install.
