### ISSUE TITLE
provision.sh has a typo on line 73

### ISSUE THREAD

**Issue by dsarytchev** [cloudfoundry-community/terraform-aws-cf-install#65]
Is: 'sudo aptitude -yq install build-essential vim-nox git unzip tree \'.
Should be: 'sudo apt-get install -yq build-essential vim-nox git unzip tree \'. 

Thanks

**Comment by dsarytchev** [comment]
This issue still exists...

**Comment by djvdorp** [comment]
I don't think this is an issue, they just prefer to use ```aptitude``` over ```apt-get``` for installing packages.

**Comment by gogolok** [comment]
Yeah, should be closed.
