### ISSUE TITLE
Perhaps a 3rd `bosh deploy` is required

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/terraform-aws-cf-install#7]
I did 10 parallel deployments into 10 AWS accounts. Of the 10 cf-install deployments - 4 didn't need the 2nd bosh deploy; 3 restarted health/0 for some reason; and 3 failed bosh deploy"Failed compiling packages" twice (thus are not successfully CF deployments)

Perhaps a 3rd `bosh deploy` is required. Or loop - testing that all VMs are running.

**Comment by teancom** [comment]
Fixed in 3680939c847582a6511576e00cada6242ac1d0e5
